name: firedoctor
version: 0.1.0-beta.4
description: Firebase diagnostics tool for Flutter. Automatically detects misconfigurations across Android, iOS, FCM, and Crashlytics with deterministic exit codes.
repository: https://github.com/yashkoladiya5/firedoctor
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  args: ^2.4.0
  meta: ^1.11.0
  path: ^1.9.0
  yaml: ^3.1.0
dev_dependencies:
  test: ^1.25.0
  mocktail: ^1.0.0
  lints: ^3.0.0
