import 'package:firedoctor/analyzers/analyzer.dart';
import 'package:firedoctor/analyzers/analyzer_context.dart';
import 'package:firedoctor/filesystem/file_system_interface.dart';
import 'package:firedoctor/models/models.dart';
import 'package:firedoctor/parsers/pubspec_parser.dart';

final class FirebaseCoreAnalyzer extends Analyzer {
  @override
  String get name => 'firebase_core';

  @override
  String get description =>
      'Analyzes Firebase Core initialization in Flutter projects';

  @override
  String get category => 'firebase_core';

  @override
  Future<DiagnosticResult> analyze(AnalyzerContext context) async {
    final startTime = DateTime.now();
    final issues = <DiagnosticIssue>[];
    final fs = context.fileSystem;
    final projectPath = context.projectPath;
    final pubspecPath = fs.join(projectPath, 'pubspec.yaml');

    if (!fs.exists(pubspecPath)) {
      return DiagnosticResult(
        analyzerName: name,
        status: CheckStatus.skipped,
        issues: issues,
        duration: DateTime.now().difference(startTime),
        timestamp: DateTime.now(),
      );
    }

    final pubspec = await PubspecParser.parseFromFile(pubspecPath, fs);
    if (pubspec == null) {
      return DiagnosticResult(
        analyzerName: name,
        status: CheckStatus.skipped,
        issues: issues,
        duration: DateTime.now().difference(startTime),
        timestamp: DateTime.now(),
      );
    }

    final libPath = fs.join(projectPath, 'lib');
    if (!fs.exists(libPath) || !fs.isDirectory(libPath)) {
      return DiagnosticResult(
        analyzerName: name,
        status: CheckStatus.skipped,
        issues: issues,
        duration: DateTime.now().difference(startTime),
        timestamp: DateTime.now(),
      );
    }

    final dartFiles = _findDartFiles(fs, libPath);
    final initCalls = <_InitCall>[];
    final ensureInitializedByFile = <String, int>{};
    final runAppByFile = <String, int>{};
    bool foundDefaultOptions = false;

    for (final filePath in dartFiles) {
      final content = fs.readAsString(filePath);
      final lines = content.split('\n');
      for (int i = 0; i < lines.length; i++) {
        final line = lines[i];
        final lineNumber = i + 1;

        if (line.contains('Firebase.initializeApp(')) {
          final initIndex = line.indexOf('Firebase.initializeApp(');
          final isAwaited =
              line.contains('await') && line.indexOf('await') < initIndex;
          initCalls.add(_InitCall(
            filePath: filePath,
            lineNumber: lineNumber,
            isAwaited: isAwaited,
          ));
        }

        if (line.contains('WidgetsFlutterBinding.ensureInitialized(')) {
          ensureInitializedByFile.putIfAbsent(filePath, () => lineNumber);
        }

        if (line.contains('runApp(')) {
          runAppByFile.putIfAbsent(filePath, () => lineNumber);
        }

        if (line.contains('DefaultFirebaseOptions.currentPlatform')) {
          foundDefaultOptions = true;
        }
      }
    }

    final hasFirebaseCore = pubspec.hasDependency('firebase_core') ||
        pubspec.hasDevDependency('firebase_core');

    final firebaseOptionsPath =
        fs.join(projectPath, 'lib', 'firebase_options.dart');
    final hasFirebaseOptionsFile = fs.exists(firebaseOptionsPath);

    if (initCalls.isEmpty && hasFirebaseCore) {
      issues.add(DiagnosticIssue(
        severity: Severity.critical,
        code: 'FD300',
        title: 'Firebase not initialized',
        description:
            'No Firebase.initializeApp() call found in any Dart file under lib/.',
        recommendation: 'Add Firebase.initializeApp() to your main.dart:\n'
            '  await Firebase.initializeApp(\n'
            '    options: DefaultFirebaseOptions.currentPlatform,\n'
            '  );',
        filePath: pubspecPath,
      ));
    }

    if (!hasFirebaseOptionsFile && hasFirebaseCore) {
      issues.add(const DiagnosticIssue(
        severity: Severity.warning,
        code: 'FD301',
        title: 'Missing firebase_options.dart',
        description: 'The lib/firebase_options.dart file does not exist. '
            'This file is generated by the Firebase CLI.',
        recommendation:
            'Run "flutterfire configure" to generate firebase_options.dart.',
      ));
    }

    if (initCalls.isNotEmpty) {
      bool shouldEmit = false;
      if (ensureInitializedByFile.isEmpty) {
        shouldEmit = true;
      } else {
        for (final call in initCalls) {
          final eiLine = ensureInitializedByFile[call.filePath];
          if (eiLine == null) {
            shouldEmit = true;
            break;
          }
          if (call.lineNumber <= eiLine) {
            shouldEmit = true;
            break;
          }
        }
      }
      if (shouldEmit) {
        issues.add(const DiagnosticIssue(
          severity: Severity.error,
          code: 'FD302',
          title: 'Missing WidgetsFlutterBinding.ensureInitialized()',
          description:
              'WidgetsFlutterBinding.ensureInitialized() should be called '
              'before Firebase.initializeApp() to ensure plugin initialization.',
          recommendation:
              'Add WidgetsFlutterBinding.ensureInitialized() before '
              'Firebase.initializeApp():\n'
              '  WidgetsFlutterBinding.ensureInitialized();\n'
              '  await Firebase.initializeApp();',
        ));
      }
    }

    if (!foundDefaultOptions && hasFirebaseCore) {
      issues.add(const DiagnosticIssue(
        severity: Severity.info,
        code: 'FD303',
        title: 'DefaultFirebaseOptions not used',
        description: 'DefaultFirebaseOptions.currentPlatform is not referenced '
            'in any Dart file. Firebase initialization should use '
            'platform-specific options.',
        recommendation: 'Pass DefaultFirebaseOptions.currentPlatform to '
            'Firebase.initializeApp():\n'
            '  await Firebase.initializeApp(\n'
            '    options: DefaultFirebaseOptions.currentPlatform,\n'
            '  );',
      ));
    }

    if (initCalls.length > 1) {
      issues.add(DiagnosticIssue(
        severity: Severity.warning,
        code: 'FD304',
        title: 'Multiple Firebase.initializeApp() calls',
        description:
            'Found ${initCalls.length} calls to Firebase.initializeApp(). '
            'Firebase should only be initialized once.',
        recommendation: 'Ensure Firebase.initializeApp() is called only once '
            'in your application.',
      ));
    }

    for (final call in initCalls) {
      if (!call.isAwaited) {
        issues.add(DiagnosticIssue(
          severity: Severity.warning,
          code: 'FD305',
          title: 'Firebase.initializeApp() should be awaited',
          description: 'Firebase.initializeApp() is called without await on '
              'line ${call.lineNumber}.',
          recommendation: 'Add await before Firebase.initializeApp():\n'
              '  await Firebase.initializeApp();',
          filePath: call.filePath,
          lineNumber: call.lineNumber,
        ));
      }
    }

    for (final call in initCalls) {
      final rAppLine = runAppByFile[call.filePath];
      if (rAppLine != null && call.lineNumber > rAppLine) {
        issues.add(DiagnosticIssue(
          severity: Severity.error,
          code: 'FD306',
          title: 'Firebase.initializeApp() after runApp()',
          description: 'Firebase.initializeApp() is called after runApp() in '
              '${call.filePath}. Firebase should be initialized before runApp().',
          recommendation: 'Move Firebase.initializeApp() before runApp() '
              'in the main function.',
          filePath: call.filePath,
          lineNumber: call.lineNumber,
        ));
      }
    }

    if (!hasFirebaseCore && initCalls.isNotEmpty) {
      issues.add(DiagnosticIssue(
        severity: Severity.error,
        code: 'FD307',
        title: 'Missing firebase_core dependency',
        description:
            'firebase_core is not listed in pubspec.yaml dependencies. '
            'It is required for all Firebase services.',
        recommendation: 'Add firebase_core to your dependencies:\n'
            '  firebase_core: ^3.0.0',
        filePath: pubspecPath,
      ));
    }

    final hasCriticalOrError = issues.any(
      (i) => i.severity == Severity.critical || i.severity == Severity.error,
    );
    final hasWarning = issues.any((i) => i.severity == Severity.warning);

    CheckStatus status;
    if (hasCriticalOrError) {
      status = CheckStatus.failed;
    } else if (hasWarning) {
      status = CheckStatus.warning;
    } else {
      status = CheckStatus.passed;
    }

    return DiagnosticResult(
      analyzerName: name,
      status: status,
      issues: issues,
      duration: DateTime.now().difference(startTime),
      timestamp: DateTime.now(),
    );
  }

  List<String> _findDartFiles(FileSystem fs, String dirPath) {
    final files = <String>[];
    if (!fs.exists(dirPath) || !fs.isDirectory(dirPath)) return files;

    for (final entry in fs.listDirectory(dirPath)) {
      if (fs.isDirectory(entry)) {
        files.addAll(_findDartFiles(fs, entry));
      } else if (entry.endsWith('.dart')) {
        files.add(entry);
      }
    }
    return files;
  }
}

final class _InitCall {
  final String filePath;
  final int lineNumber;
  final bool isAwaited;

  const _InitCall({
    required this.filePath,
    required this.lineNumber,
    required this.isAwaited,
  });
}
